function bases = makeSmoothTemporalBasis_fromStruct(settings_struct, binfun)
% function bases = makeSmoothTemporalBasis_fromStruct(settings_struct, binfun)

bases = basisFactory.makeSmoothTemporalBasis( ...
    settings_struct.type,...
    settings_struct.duration,...
    settings_struct.nBasis,...
    binfun,...
    settings_struct.nlOffset);
